#!/bin/bash
# Wrapper script for running ansible-playbook with 1Password integration and environment variable support.
# Usage: ./ansible-playbookw <playbook> [extra ansible-playbook args...]

playbook="${1:?Usage: $0 <playbook> [extra args...]}"
shift

SECRETS_FILE="$(dirname "$playbook")/secrets.env"
if [ -f "$SECRETS_FILE" ]; then
  SECRETS_ARG="--env-file $SECRETS_FILE"
else
  SECRETS_ARG=""
fi

op run --no-masking $SECRETS_ARG --env-file ./globals.env -- \
  ansible-playbook \
  "./$playbook" "$@"
